gem:
  exclude:
    - rubocop
    - rubocop-rails
    - rubocop-performance
    - rubocop-packaging
    - rubocop-ast
    - erb-formatter
    - tzinfo-data
    - sorbet
    - tapioca
    - ruby-lsp
    - ruby-lsp-rails
    - prism
    - rdoc
dsl:
annotations:
  typed_overrides:
    graphql: "ignore"
